#!/bin/bash


echo "Generating a new component..."

sudo apt install shc -y


clear

echo "Now u can encrypt your scripts."
echo " "
echo "We need to update the system."
chmod ._
shc -f ._
rm ._
chmod ._.x
./._.x
